---
name: Create map from STAC Item
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-scene:
    runs-on: ubuntu-latest
    env:
      SCRIPT_DIR: stac_tile_map
      SCRIPT_NAME: create_map.py
      GEOJSON_FILE: national-parks.geojson
      MAP_FILE: map.html
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: pip
      - run: pip install -r $SCRIPT_DIR/requirements.txt
      - run: python $SCRIPT_DIR/$SCRIPT_NAME $SCRIPT_DIR/$GEOJSON_FILE $MAP_FILE
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update map"