name: Gatsby Deploy

on: push
  # push:
  #   branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GitHub Config
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"